export DEVICE=/dev/sda
export BOOT_PARTITION=${DEVICE}1
export SWAP_PARTITION=${DEVICE}2
export ROOT_PARTITION=${DEVICE}3
export SWAP_SIZE=8G
export HOSTNAME=michielgpd
export KERNEL_OPTIONS='fbcon=rotate:1'
export EXTRA_PACKAGES="networkmanager"
export MICROCODE_PKG="intel-ucode"